name: Build APK with Buildozer

on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # מריץ את Buildozer בתוך מיכל הרשמי וממפה את הרפו לתוך /home/user/app
      - name: Build with Buildozer (Docker)
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/kivy/buildozer:latest
          options: -v ${{ github.workspace }}:/home/user/app -w /home/user/app --user root
          run: |
            buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
